use reqwest::Client;
use crate::terminal_ui::TerminalStyle;
use serde_json::json;
use std::env;
use std::fs;
use std::io;
use std::process::Command;

pub async fn deploy_to_looker() -> Result<String, Box<dyn std::error::Error>> {
    let cfg = LookerAutoConfig::from_env()?;
    let quick_link = cfg.quick_link();

    // 1. Read JSON generated by pipeline to ensure the report exists.
    let report_json = fs::read_to_string(&cfg.report_json_path)?;
    let _report_preview: serde_json::Value = serde_json::from_str(&report_json)?;

    // 2. Upload cleaned CSV into BigQuery table.
    upload_clean_csv(&cfg).await?;

    // 3. Try creating a Looker Studio report through API.
    let client = Client::new();
    let looker_payload = json!({
        "name": format!("projects/{}/reports/{}", cfg.project_id, cfg.report_id),
        "displayName": cfg.report_name,
        "dataSourceIds": [format!("bq://{}.{}.{}", cfg.project_id, cfg.dataset_id, cfg.table_id)],
        "configuration": {
            "charts": [
                {"type": "bar", "title": "Revenue by Region", "x": "region", "y": "revenue_per_txn"},
                {"type": "line", "title": "Rating Trends", "x": "date", "y": "rating_star"},
                {"type": "table", "title": "Outlier Detection", "columns": ["outlier_flag", "revenue"]}
            ],
            "refreshInterval": "5m"
        }
    });

    let token = get_gcloud_token()?;
    let api_result = client
        .post(&cfg.looker_api_endpoint)
        .header("Authorization", format!("Bearer {}", token))
        .json(&looker_payload)
        .send()
        .await;

    write_quick_link_file(&cfg, &quick_link)?;

    match api_result {
        Ok(res) => match res.error_for_status() {
            Ok(ok_res) => {
                let body = ok_res.json::<serde_json::Value>().await?;
                let report_url = body["name"]
                    .as_str()
                    .and_then(|id| id.split('/').next_back())
                    .map(|report_id| format!("https://lookerstudio.google.com/reporting/{}", report_id))
                    .unwrap_or_else(|| build_manual_looker_url());
                write_manual_connect_file(&cfg, &report_url)?;
                print_quick_link_summary(&cfg, &quick_link);
                println!("LIVE LOOKER STUDIO: {}", report_url);
                Ok(report_url)
            }
            Err(err) => {
                let manual_url = build_manual_looker_url();
                write_manual_connect_file(&cfg, &manual_url)?;
                print_quick_link_summary(&cfg, &quick_link);
                println!(
                    "LOOKER API unavailable ({}). Buka manual: {}",
                    err, manual_url
                );
                Ok(manual_url)
            }
        },
        Err(err) => {
            let manual_url = build_manual_looker_url();
            write_manual_connect_file(&cfg, &manual_url)?;
            print_quick_link_summary(&cfg, &quick_link);
            println!(
                "LOOKER API request failed ({}). Buka manual: {}",
                err, manual_url
            );
            Ok(manual_url)
        }
    }
}

async fn upload_clean_csv(cfg: &LookerAutoConfig) -> Result<(), Box<dyn std::error::Error>> {
    let status = Command::new("bq")
        .args([
            "load",
            "--source_format=CSV",
            "--autodetect",
            "--project_id",
            &cfg.project_id,
            &format!("{}.{}", cfg.dataset_id, cfg.table_id),
            &cfg.clean_csv_path,
        ])
        .status()?;

    if !status.success() {
        return Err("bq load failed".into());
    }

    println!("BigQuery LOADED!");
    Ok(())
}

fn get_gcloud_token() -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new("gcloud")
        .args(["auth", "print-access-token"])
        .output()?;

    if !output.status.success() {
        return Err("gcloud auth print-access-token failed".into());
    }

    let token = String::from_utf8(output.stdout)?;
    let token = token.trim().to_string();
    if token.is_empty() {
        return Err("empty gcloud token".into());
    }

    Ok(token)
}

struct LookerAutoConfig {
    project_id: String,
    dataset_id: String,
    table_id: String,
    report_id: String,
    report_name: String,
    clean_csv_path: String,
    report_json_path: String,
    looker_api_endpoint: String,
}

impl LookerAutoConfig {
    fn from_env() -> Result<Self, Box<dyn std::error::Error>> {
        let project_id = required_env("LOOKER_GCP_PROJECT_ID")?;
        let dataset_id = optional_env("LOOKER_BQ_DATASET", "dataset_transaksi_ecommerce");
        let table_id = optional_env("LOOKER_BQ_TABLE", "dataset_transaksi_ecommerce");
        let report_id = optional_env("LOOKER_STUDIO_REPORT_ID", "ecommerce_dashboard");
        let report_name = optional_env(
            "LOOKER_STUDIO_REPORT_NAME",
            "E-Commerce Analytics | Polars Cleaned",
        );
        let clean_csv_path = optional_env(
            "LOOKER_CLEAN_CSV_PATH",
            "./output/csv/dataset_transaksi_ecommerce.csv",
        );
        let report_json_path = optional_env("LOOKER_REPORT_JSON_PATH", "./output/html/report_data.json");
        let looker_api_endpoint = optional_env(
            "LOOKER_STUDIO_API_ENDPOINT",
            "https://lookerstudio.googleapis.com/v1alpha/reports",
        );

        Ok(Self {
            project_id,
            dataset_id,
            table_id,
            report_id,
            report_name,
            clean_csv_path,
            report_json_path,
            looker_api_endpoint,
        })
    }

    fn quick_link(&self) -> String {
        format!(
            "https://lookerstudio.google.com/reporting/create?c.datasource=bigquery&c.queryConfig={{\"projectId\":\"{}\",\"datasetId\":\"{}\",\"tableId\":\"{}\",\"useStandardSql\":true}}",
            self.project_id, self.dataset_id, self.table_id
        )
    }
}

fn required_env(name: &str) -> Result<String, Box<dyn std::error::Error>> {
    let value = env::var(name).map_err(|_| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("Missing environment variable: {name}"),
        )
    })?;
    let trimmed = value.trim().to_string();
    if trimmed.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("Environment variable is empty: {name}"),
        )
        .into());
    }
    Ok(trimmed)
}

fn optional_env(name: &str, default_value: &str) -> String {
    env::var(name)
        .ok()
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
        .unwrap_or_else(|| default_value.to_string())
}

fn build_manual_looker_url() -> String {
    "https://lookerstudio.google.com/navigation/reporting/create".to_string()
}

fn write_manual_connect_file(
    cfg: &LookerAutoConfig,
    looker_url: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let bq_console = format!(
        "https://console.cloud.google.com/bigquery?project={}&p={}&d={}&t={}&page=table",
        cfg.project_id, cfg.project_id, cfg.dataset_id, cfg.table_id
    );

    let content = format!(
        "Looker Studio Quick Link:\n{}\n\nBigQuery Table:\n{}.{}.{}\n\nOpen in BigQuery Console:\n{}\n",
        looker_url, cfg.project_id, cfg.dataset_id, cfg.table_id, bq_console
    );

    fs::create_dir_all("./output/looker_studio")?;
    fs::write("./output/looker_studio/looker_manual_connect.txt", content)?;
    Ok(())
}

fn write_quick_link_file(
    cfg: &LookerAutoConfig,
    quick_link: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let content = format!(
        "Looker Studio Quick Link:\n{}\n\nProject: {}\nDataset: {}\nTable: {}\n",
        quick_link, cfg.project_id, cfg.dataset_id, cfg.table_id
    );

    fs::create_dir_all("./output/looker_studio")?;
    fs::write("./output/looker_studio/looker_quick_link.txt", content)?;
    Ok(())
}

fn print_quick_link_summary(cfg: &LookerAutoConfig, quick_link: &str) {
    let ui = TerminalStyle::detect();
    println!("\n{}", ui.success("PIPELINE SELESAI"));
    println!("{}", ui.divider(50));
    println!("CSV Cleaned : {}", cfg.clean_csv_path);
    println!(
        "HTML Report : {}",
        cfg.report_json_path.replace("report_data.json", "report.html")
    );
    println!("BigQuery    : Terunggah ke project {}", cfg.project_id);
    println!("{}", ui.divider(50));
    println!("{}", ui.header("BUAT DASHBOARD LOOKER STUDIO SEKARANG:"));
    println!("{}", ui.info(quick_link));
    println!("{}", ui.divider(50));
}